platform :ios, '13.0'
use_frameworks!

target 'OpenZhixueStudent' do
  pod 'Alamofire', '~> 5.8'
  pod 'Kingfisher', '~> 7.10'
  pod 'SQLite.swift', '~> 0.14'
  pod 'Charts', '~> 5.0'
  pod 'Combine', '~> 1.0'
  pod 'SnapKit', '~> 5.6'
  pod 'KeychainAccess', '~> 4.2'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'ObjectMapper', '~> 4.2'
  pod 'RxSwift', '~> 6.5'
  pod 'RxCocoa', '~> 6.5'
end

target 'OpenZhixueStudentTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
